### ISSUE TITLE
My minecraft skin gave my friend a virus warning

### ISSUE THREAD

**Issue by FakeNeth** [minotar/minotar.net#12]
Apparently one of my friends was browsing a google doc in Google Chrome, and out of no where he got this virus warning on his pc - http://prntscr.com/ebug6p

That's my minecraft account/skin, which is really odd since all he was doing was browsing a google doc and my skin pops up as a virus warning.  

Can someone clarify what might have caused this? Would appreciate it; I'm not too knowledgeable about web development so would like to know what caused my skin (which we still can't figure out why my skin is involved) to throw him a virus warning.

Thank you.

**Comment by connor4312** [comment]
I've seen reports of that on a few other unrelated sites I work on. Avast seems to have rolled an update that's causing issues for some people, hopefully they'll release a fix.

Personally I would recommend disabling Avast's MITM proxy, antiviruses are notorious for having security vulnerabilities and adding them as a root CA is a recipe for disaster.
