### ISSUE TITLE
Site is offline

### ISSUE THREAD

**Issue by Malachiel87** [minotar/minotar.net#16]
Just notice in this morning the site was offline

**Comment by LukeHandle** [comment]
It appears the registration has lapsed :( 

I've poked @clone1018 who should be waking up soon.

> Domain Name: MINOTAR.NET
Registry Domain ID: 1649602748_DOMAIN_NET-VRSN
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: http://www.namecheap.com
Updated Date: 2019-03-23T14:03:41Z
Creation Date: 2011-04-07T01:07:18Z
**Registry Expiry Date: 2020-04-07T01:07:18Z**

**Comment by clone1018** [comment]
I renewed the domain a second ago, should be coming back online soon. Sorry
for the inconveniences!

**Comment by Malachiel87** [comment]
Thank you, is all working now :)
