### ISSUE TITLE
Site offline

### ISSUE THREAD

**Issue by AlwaysHAK** [minotar/minotar.net#18]
Hello,

The minotar.net website has gone down with [this error](https://gyazo.com/df92fcf8768f17e2a80537572582df5f)

**Comment by LukeHandle** [comment]
Hi there,

I've also raised an issue over here https://github.com/minotar/imgd/issues/205 and @clone1018 is aware.

**Comment by clone1018** [comment]
Sorry about that, just renewed the domain. Should be starting to resolve again now!

**Comment by LukeHandle** [comment]
I saw this fixed fairly quickly, and now at 48 hours since, it should be resolved for nearly everyone.

Global DNS checker site reports the Cloudflare IPs correctly (and did within the first hour or so) - https://www.whatsmydns.net/#A/minotar.net
