### ISSUE TITLE
Steve again

### ISSUE THREAD

**Issue by TomgraPl** [minotar/minotar.net#19]
So I'm trying to get my friend's avatar, and I get Steve. I tried using the uuid, but with no effect. I checked on namemc nad in-game, and he does have a custom skin, but minotar shows Steve's head.
It works fine with my own avatar, my skin's head appears.

**Comment by LukeHandle** [comment]
I've checked and everything is back to normal. There were some peaks in traffic though which I can see triggered some rate limiting today.

**Comment by LukeHandle** [comment]
Closing this out. We've since made some improvements which should make this rarer.
