### ISSUE TITLE
Skins not loading & displaying Steves

### ISSUE THREAD

**Issue by KTibow** [minotar/minotar.net#24]
For example, [my user is valid](https://mcuuid.net/?q=KTibow), yet [I still see a Steve](https://minotar.net/avatar/KTibow/64). Is this a rate limiting thing?

**Comment by LukeHandle** [comment]
Hi @KTibow, thanks for flagging this, looks like we're seeing an issue with another service which I expect is related. I've flagged this with them and will follow-up in the morning.

**Comment by LukeHandle** [comment]
Cool, normal skin is loading correctly now 👍
